name: Build and Release Snap

on:
  push:
    branches:
    - master

jobs:
  build-snap:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        architecture:
        - linux/amd64
#        - linux/386
#        - linux/arm64
#        - linux/arm/v7
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        path: phockup

    - id: build
      name: Build
      run: |
        # Enable docker daemon support for --platform parameter
        echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json > /dev/null
        sudo systemctl restart docker

        # Configure qemu-user-static
        docker run --rm --tty \
          --security-opt apparmor:unconfined \
          --cap-add SYS_ADMIN \
          multiarch/qemu-user-static --reset -p yes

        # Run snapcraft
        docker run --rm --tty \
          --security-opt apparmor:unconfined \
          --cap-add SYS_ADMIN \
          --device /dev/fuse \
          --volume /sys \
          --volume /sys/fs/cgroup:/sys/fs/cgroup:ro \
          --volume $GITHUB_WORKSPACE/phockup:$GITHUB_WORKSPACE/phockup \
          --workdir $GITHUB_WORKSPACE/phockup \
          --platform "${{ matrix.architecture }}" \
          --env PLAYTEST="${{ matrix.playtest }}" \
          diddledan/snapcraft:core18

        SNAP=$(find $GITHUB_WORKSPACE/phockup -maxdepth 1 -type f -name "*.snap" | head -n1)
        echo $SNAP
        echo ::set-output name=snap::$SNAP
